"""empty message

Revision ID: 6306d1fc601a
Revises: 
Create Date: 2023-02-10 12:11:03.965438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6306d1fc601a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ex_dung_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ex_dung_table',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('dunghihi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ex_table_dung_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
