"""empty message

Revision ID: af1bb7640190
Revises: 6306d1fc601a
Create Date: 2023-02-10 12:44:46.086085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af1bb7640190'
down_revision = '6306d1fc601a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ex_dung_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ex_dung_table',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('dunghihi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ex_table_dung_pkey')
    )
    op.drop_table('results')
    # ### end Alembic commands ###
